"""초기 주문 원장과 전략 저장 구조

Revision ID: 87b498dada4b
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "87b498dada4b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_states",
        sa.Column("mode", sa.String(length=12), nullable=False),
        sa.Column("capital", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("high_water", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("daily_anchor", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("trading_day", sa.String(length=10), nullable=False),
        sa.Column("halted", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("mode"),
    )
    op.create_table(
        "backtest_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_backtest_jobs_status"), "backtest_jobs", ["status"], unique=False)
    op.create_table(
        "candles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=24), nullable=False),
        sa.Column("interval", sa.String(length=4), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "interval", "timestamp"),
    )
    op.create_index(op.f("ix_candles_symbol"), "candles", ["symbol"], unique=False)
    op.create_index(op.f("ix_candles_timestamp"), "candles", ["timestamp"], unique=False)
    op.create_table(
        "commands",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_commands_status"), "commands", ["status"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("strategy_id", sa.String(length=36), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("notify", sa.Boolean(), nullable=False),
        sa.Column("sent", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_created_at"), "events", ["created_at"], unique=False)
    op.create_table(
        "ledger",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("intent_id", sa.String(length=36), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("amount", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("costs", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint"),
    )
    op.create_index(op.f("ix_ledger_intent_id"), "ledger", ["intent_id"], unique=False)
    op.create_table(
        "order_intents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("strategy_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=12), nullable=False),
        sa.Column("symbol", sa.String(length=24), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("broker_id", sa.String(length=256), nullable=True),
        sa.Column("filled_quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("filled_amount", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("costs", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("costs_final", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_id"),
    )
    op.create_index(op.f("ix_order_intents_mode"), "order_intents", ["mode"], unique=False)
    op.create_index(op.f("ix_order_intents_status"), "order_intents", ["status"], unique=False)
    op.create_index(op.f("ix_order_intents_strategy_id"), "order_intents", ["strategy_id"], unique=False)
    op.create_table(
        "runtime_state",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=12), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_snapshots_created_at"), "snapshots", ["created_at"], unique=False)
    op.create_index(op.f("ix_snapshots_mode"), "snapshots", ["mode"], unique=False)
    op.create_table(
        "strategies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=24), nullable=False),
        sa.Column("mode", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_strategies_symbol"), "strategies", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_strategies_symbol"), table_name="strategies")
    op.drop_table("strategies")
    op.drop_index(op.f("ix_snapshots_mode"), table_name="snapshots")
    op.drop_index(op.f("ix_snapshots_created_at"), table_name="snapshots")
    op.drop_table("snapshots")
    op.drop_table("runtime_state")
    op.drop_index(op.f("ix_order_intents_strategy_id"), table_name="order_intents")
    op.drop_index(op.f("ix_order_intents_status"), table_name="order_intents")
    op.drop_index(op.f("ix_order_intents_mode"), table_name="order_intents")
    op.drop_table("order_intents")
    op.drop_index(op.f("ix_ledger_intent_id"), table_name="ledger")
    op.drop_table("ledger")
    op.drop_index(op.f("ix_events_created_at"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_commands_status"), table_name="commands")
    op.drop_table("commands")
    op.drop_index(op.f("ix_candles_timestamp"), table_name="candles")
    op.drop_index(op.f("ix_candles_symbol"), table_name="candles")
    op.drop_table("candles")
    op.drop_index(op.f("ix_backtest_jobs_status"), table_name="backtest_jobs")
    op.drop_table("backtest_jobs")
    op.drop_table("account_states")
    # ### end Alembic commands ###
